config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"

  root "static_pages#home"
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :microposts, only: [:create, :destroy, :show]

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  default_scope -> { order('created_at DESC') } # ORDER BY CREATED AT DESC
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  validates :image, content_type:  {in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format"},
                                    size: {less_than: 5.megabytes,
                                    message: "should be less than 5MB"}
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create,:destroy]
  before_action :correct_user, only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:success]="Micropost created!"
      redirect_to root_url
    else
      @feed_items =[]
      render 'static_pages/home'
    end

  end

  def show
    @micropost = Micropost.find(params[:id])
  end
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?

    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end


  # def destroy
  #   @micropost.destroy
  #   binding.pry
  #   flash[:success]="Micropost deleted"
  #   redirect_to request.referrer || root_url
  # end

  private
  def micropost_params
    params.require(:micropost).permit(:content , :image)
  end

  def correct_user
    @micropost=current_user.microposts.find_by(id:params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size:50), micropost.user%>
  <span class="user"><%= link_to  micropost.user.name, micropost.user%></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.image.variant(resize_to_limit: [500,500] ) if micropost.image.attached? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "View Post", micropost_path(micropost), method: :delete,
              data: { confirm: "Are you sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/show.html.erb
<h1>Micropost</h1>
<p><%= @micropost.content %></p>
<p>Posted by: <%= @micropost.user.name %></p>
<%= link_to 'Back', request.referrer || root_path %>